POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###
GET http://localhost:8000/products/201539b7-528e-45de-9883-d601344eb0c7
Content-Type: application/json

####
PUT http://localhost:8000/products/201539b7-528e-45de-9883-d601344eb0c7
Content-Type: application/json

{
    "name": "My Product Updated",
    "price": 200
}

###
DELETE  http://localhost:8000/products/201539b7-528e-45de-9883-d601344eb0c7

###
GET http://localhost:8000/products