basePath: /
host: localhost:8000
info:
  contact:
    email: osni.antonio@gmail.com
    name: Osni Antônio Küchler
    url: https://www.linkedin.com/in/osni-ant%C3%B4nio-k%C3%BCchler-5487b13b
  description: Product API with authentication
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
